# -*- coding: utf-8 -*-

{
    'name': 'ALA Educational ERP Core',
    'version': '19.0.1.0.0',
    'category': 'School',
    'summary': """Core Module of Educational ERP""",
    'description': """A strong and complete user-friendly ERP solution designed 
     specifically for school administration is Educational ERP. 
     Details such as student entrance, enrollment information, faculty records, 
     class management, and subject administration are simple to administer.""",
    'author': 'Alanniainfotechz',
    'company': 'Alanniainfotechz',
    'maintainer': 'Alanniainfotechz',
    'depends': ['stock', 'hr_recruitment', 'contacts','base','spreadsheet_dashboard', 'calendar',
                'contacts', 'hr', 'mail', 'website'],
    'data': [
        'security/education_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/activity.xml',
        'wizard/application_reject_views.xml',
        'wizard/tc_issue_view.xml',
        'wizard/id_card_wizard_view.xml',
        # 'wizard/ad_no_import_view.xml',
        'views/education_main_menu.xml',
        # 'wizard/rank_card_wizard_view.xml',
        # 'views/res_partner_views.xml',
        'views/education_academic_year_views.xml',
        'views/education_application_views.xml',
        'views/education_class_views.xml',
        'views/education_class_division_views.xml',
        'views/education_student_views.xml',
        # 'views/stuent_teachers_id_view.xml',
        'views/education_faculty_views.xml',
        'views/education_document_views.xml',
        'views/document_document_views.xml',
        'views/education_division_views.xml',
        'views/education_medium_views.xml',
        'views/education_subject_views.xml',
        # 'views/education_syllabus_views.xml',
        'views/education_amenities_views.xml',
        # 'views/res_company_views.xml',
        'views/hr_applicant_views.xml',
        'views/application_reject_reason_views.xml',
        'views/grenn_book_view.xml',
        'views/privacy_policy.xml',
        'views/student_verify_template.xml',
        'report/student_id_card_reports.xml',
        'report/application_ir_action.xml',
        'report/id_ir_actions_report.xml',
        'report/student_application_reports.xml',
        'report/faculty_id_card_reports.xml',
        'report/division_id_card_template.xml',
        'report/id_card_student_temp.xml',
        # 'report/rank_card_action.xml',
        # 'report/rank_card_template.xml',
        # 'views/login_logo.xml',
    ],

    # 'assets': {
    #     'web.assets_backend': [
    #         'ala_education_core/static/src/lib/cropper/cropper.css',
    #         'ala_education_core/static/src/lib/cropper/cropper.js',
    #         'ala_education_core/static/src/js/camera_crop.js',
    #         'ala_education_core/static/src/xml/camera_crop.xml',
    #         'ala_education_core/static/src/css/camera.css',
    #     ],
    # },

    'demo': [
        'demo/education_academic_year_demo.xml'
    ],
    'images': ['static/description/banner.jpg'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
